INCLUDEPATH += $$PWD

LIBMAGIC=-lmagic
QMAGIC_LIBNAME = QMagic
LIB_QMAGIC = -lQMagic -lmagic
#QMAGIC_LIBDIR  = $$OUT_PWD
#LIBS += -L$$QMAGIC_LIBDIR -l$$QMAGIC_LIBNAME
#unix:QMAKE_RPATHDIR += $$QMAGIC_LIBDIR

