INCLUDEPATH += $$PWD

RENAME_DIALOG_LIBNAME = RenameDialog
#SPOTLIGHT_WIDGET_LIBDIR  = $$OUT_PWD
#LIBS += -L$$RENAME_DIALOG_LIBDIR -l$$RENAME_DIALOG_LIBNAME
#unix:QMAKE_RPATHDIR += $$RENAME_DIALOG_LIBDIR

