INCLUDEPATH += $$PWD

SPOTLIGHT_WIDGET_LIBNAME = SpotlightWidget
#SPOTLIGHT_WIDGET_LIBDIR  = $$OUT_PWD


#LIBS += -L$$SPOTLIGHT_WIDGET_LIBDIR -l$$SPOTLIGHT_WIDGET_LIBNAME

unix:QMAKE_RPATHDIR += $$SPOTLIGHT_WIDGET_LIBDIR

